### ISSUE TITLE
Status formatting

### ISSUE THREAD

**Issue by ghost** [DiNitride/Discord-Music-Status#25]
Are there any means to change the formatting of the output? The bot doesn't follow the Snip.txt format of `“song title” ― artist` instead the output is `song title artist` which seems untidy at best.

My preferred output would be something like `♪ “Two Weeks” ― All That Remains ♪` so users know I'm listening to a song, and not making a worrying status (i.e; I cum blood by Cannibal Corpse haha). I've never used Python before, I can understand it by looking through it but wouldn't know what or where to change for these to take effect.

**Comment by DiNitride** [comment]
As you can see by the screenshots in the README.md, it does follow snips format, as that is how mine displays. I am not sure why yours would be any different. What it displays in the console =/= what will show on discord, due to the fact I have to do some bootleg encoding stuff to get it to display in the console without crashing. 

If you wish to edit how the program displays on Discord, you can do so by editing this line

`await bot.change_presence(afk=True, status=discord.Status.invisible, game=discord.Game(name=song))`

https://github.com/DiNitride/Discord-Music-Status/blob/master/run.py#L92

You can replace `song` with an fstring with the formatting you want like so.
`f"prefix {song} suffix@`
Wherever `{song}` is inside the fstring, it will display snips output. The string must be declared an fstring by prefixing the string with an `f` (`f""`)

**Comment by ghost** [comment]
Ah, I thought what displayed in the console was what Discord was being fed. Thanks for the instant reply and clarification 😄
