### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Hexality** [DiNitride/Discord-Music-Status#37]
![image](https://user-images.githubusercontent.com/17398632/34128265-3d2387e6-e427-11e7-96c5-52a69c215e71.png)
how i fix this?

**Comment by DiNitride** [comment]
Update to Python 3.6, it's in the requirements

**Comment by Hexality** [comment]
I'm sorry for bothering you so muchbut ...
![image](https://user-images.githubusercontent.com/17398632/34131047-362794c8-e431-11e7-8ffb-e38c6563348a.png)
how i fix this?

**Comment by Hexality** [comment]
i use discord canary

**Comment by DiNitride** [comment]
You have not installed the requirements for the program, please refer to the install guide

**Comment by Hexality** [comment]
yes, i already installed all the requirements, but doesn't work

**Comment by DiNitride** [comment]
No, you have not. You are missing the discord.py python package, hence the
error. Installing Discord itself does not equal installing the python
requirements for this program. The error says you have no module called
Discord, therefore you haven't installed it via Pip.

On 18 Dec 2017 23:37, "LinuxGamer" <notifications@github.com> wrote:

yes, i already installed all the requirements, but doesn't work

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/DiNitride/Discord-Music-Status/issues/37#issuecomment-352592544>,
or mute the thread

**Comment by Hexality** [comment]
but, it's installed

**Comment by Hexality** [comment]
![image](https://user-images.githubusercontent.com/17398632/34133586-bd118934-e43c-11e7-9e07-47e6af6d7134.png)

**Comment by DiNitride** [comment]
Okay, when you say 'it' is installed. Do you mean,
Discord, the application you use to talk to people,
Or
Discord.py, the python library for using the Discord API with Python

**Comment by Hexality** [comment]
Discord.py and Discord

**Comment by Hexality** [comment]
Anyway, thank you. probably should be a glitch in the windows settings, thanks for the help.

**Comment by DiNitride** [comment]
If you have Discord.py installed then you need to make sure that the Python
interpreter you are using has access to it

**Comment by Hexality** [comment]
well, I'll test it on another computer later, I'd already tried using other scripts here and they also did not work, it probably should be some internal glitch. Well, thank you anyway.
