### ISSUE TITLE
I'm doing something wrong...

### ISSUE THREAD

**Issue by sjorsofzo** [DiNitride/Discord-Music-Status#42]
Alright, so I've installed python, snip and the Discord Status master.

Ran the run.py command and it says a config file is supposed to show up somewhere? I did not get anything and tried editing the run.py itself with 

config = configparser.ConfigParser()

token = MTQ3---rest of the key
snip = C:\Users\Sjors\Desktop\Snip\Snip.txt

but this still didn't do anything for me, logbook and discord.py are up to date and I've also upgraded it. Checked to see if my discord was displaying anything from a different account and it wasn't. 

So something is going wrong with the config file. I just don't really know what I'm supposed to do

Thanks in advance

**Comment by USGIshimura** [comment]
I been trying to set up this tool for months now. The instructions are very ignorant and not very helpful. Like, 4. 5. 6. points doesnt even make sence. And as somebody who never used phyton before Installing Logbook and Discord via Pip what does it even mean, run command promp? Well, those commands doesnt work in cmd promp. Like i said, poor and ignorant instructions.

**Comment by DiNitride** [comment]
@sjorsofzo 
1. Revert any changes you've made to the source code, if you don't it may produce random errors.
2. If a config file isn't being created when you initially run it, then either the program does not have permissions to create files, or another error is happening before the code to create the file is reached. Try running the program directly in a console with `python run.py` or open it in IDLE and run via there.

@USGIshimura Months? Have you even made an issue at any point? Have you tried getting any help? 

`"what does it even mean, run command promp?"` - I expect people trying to download source code from Github and run it to have a basic understanding of how their operating system works and how to use it effectively. If you do not understand what a command prompt (Terminal, Cmd, etc) is, then that is beyond the scope of this programs instructions and are areas you need to Google. If you feel there is genuinely something missing from the instructions other than your own lack of understanding, then feel free to raise an issue on with me.

Regarding your statement of instructions 4, 5 and 6, let me explain.
`4. Run run.py to generate a config file` - I'm not entirely sure how this doesn't make sense. Run the file. Have you downloaded it? have you got Python installed? This isn't special programmer terminology, this is basic usage of a computer.
`5. Configure the file with your token and path to snip.txt Neither should have quotation marks` - Configure, i.e. edit and add information, to the config file the run.py file generates on it's first run when there is not a config file. Should a config file not be generated, please see my above answer to @sjorsofzo.
`6. Start run.py` - See explanation to 4.

**Comment by CatGuppy** [comment]
@USGIshimura I followed the instructions easily enough, so I don't understand how you can't get this running. 

Install Python 3.6.
Install the modules.
Install Snip and open it.
Run the run.py (it creates the config).
Edit the config file with the token from your Discord and the full directory to Snip.txt in the snip section.
Run run.py again, and it goes through the credential handshake for your token. Then you get a message saying Discord Music is ready to start.

![reece](https://user-images.githubusercontent.com/35075104/34533305-98ec0242-f0b1-11e7-9c05-6a0cb08ee030.png)

Double check that you don't have two versions of Python installed because debugger may be running from one directory and the modules you installed with pip could be in another Python folder on your PC. If that's the case it will give you the can't find discord module error because it can't see them.

**Comment by DiNitride** [comment]
Closed because of no response
