### ISSUE TITLE
You don't *need* Snip!

### ISSUE THREAD

**Issue by BunnyHelp** [DiNitride/Discord-Music-Status#56]
This really should be emphasized more in the "readme"!
I spent hours upon hours trying to figure out why Snip was outputting my artist / song title incorrectly with Winamp. It always ended up weird and corrupted [like this](https://puu.sh/AG5EJ/15a48dd6dd.gif), and when I made a post on Snip's GitHub, I didn't really get any help.

I finally ended up installing [this plugin for Winamp](http://amip.tools-for.net/wiki/start), configured it to spit out an output file of what's playing, and it's now working like an absolute charm =^]

I hope other users could benefit from this same Winamp plugin as I have!

**Comment by DiNitride** [comment]
After my exams are finished and I rewrite the script, I'll make sure to
link some other methods of getting song data from different players, so
it's more cross-platform rather than linking a windows only method.

Regarding Snip, there could have been a Winamp update that has caused the
issue.

It does currently say in the README that any text file can be used, but
like I said when I rewrite I'll make it clearer

**Comment by DiNitride** [comment]
> Due to Snip being Windows only, the default install instructions will only be applicable for Windows. However as the script is Python, as long as you find some program to spit out your music to a text file, you can configre that text file instead and it will run on any machine Python will run on

From the README.md
